<?php
/**
 * This is the language file for the 'EDMdesigner' addon.
 *
 * @package Interspire_Addons
 * @subpackage Addons_edmdesigner
 */

define("LNG_Addon_edmdesigner_Menu_ManageCampaigns", "Manage responsive campaigns");
define("LNG_Addon_edmdesigner_Menu_NewCampaign", "New responsive campaign");
define("LNG_Addon_edmdesigner_Menu_ManageTemplates", "Manage responsive templates");
define("LNG_Addon_edmdesigner_Menu_NewTemplate", "New responsive template");




//l10n projectListVM
define("LNG_Addon_edmdesigner_projectListVM_Title-Templates", "Templates");
define("LNG_Addon_edmdesigner_projectListVM_Title-BuiltInTemplates", "Built-in Templates");
define("LNG_Addon_edmdesigner_projectListVM_Title-Campaigns", "Campaigns");

define("LNG_Addon_edmdesigner_projectListVM_NewProject-Template", "New template");
define("LNG_Addon_edmdesigner_projectListVM_NewProject-BuiltInTemplate", "New built-in template");
define("LNG_Addon_edmdesigner_projectListVM_NewProject-Campaign", "New campaign");

define("LNG_Addon_edmdesigner_projectListVM_Headings_Title", "Title");
define("LNG_Addon_edmdesigner_projectListVM_Headings_Category", "Category");
define("LNG_Addon_edmdesigner_projectListVM_Headings_Subject", "Subject");
define("LNG_Addon_edmdesigner_projectListVM_Headings_Active", "Active");
define("LNG_Addon_edmdesigner_projectListVM_Headings_Archive", "Archive");
define("LNG_Addon_edmdesigner_projectListVM_Headings_CreatedAt", "Created at");
define("LNG_Addon_edmdesigner_projectListVM_Headings_ModifiedAt", "Modified at");
define("LNG_Addon_edmdesigner_projectListVM_Headings_Actions", "Actions");

define("LNG_Addon_edmdesigner_projectListVM_Actions_Open", "Edit");
define("LNG_Addon_edmdesigner_projectListVM_Actions_EditCampaignInfo", "Campaign info");
define("LNG_Addon_edmdesigner_projectListVM_Actions_SendCampaign", "Send");
define("LNG_Addon_edmdesigner_projectListVM_Actions_Preview", "View");
define("LNG_Addon_edmdesigner_projectListVM_Actions_Duplicate", "Copy");
define("LNG_Addon_edmdesigner_projectListVM_Actions_Remove", "Delete");

define("LNG_Addon_edmdesigner_projectListVM_Pagination_Back", "Back");
define("LNG_Addon_edmdesigner_projectListVM_Pagination_Next", "Next");
define("LNG_Addon_edmdesigner_projectListVM_Pagination_ResultsPerPage", "Results per page: ");
define("LNG_Addon_edmdesigner_projectListVM_Pagination_ActPage", "Page");




//l10n previewVM
define("LNG_Addon_edmdesigner_previewVM_Title-Template", "Preview template");
define("LNG_Addon_edmdesigner_previewVM_Title-BuiltInTemplate", "Preview built-in template");
define("LNG_Addon_edmdesigner_previewVM_Title-Campaign", "Preview campaign");

define("LNG_Addon_edmdesigner_previewVM_Mobile", "Mobile");
define("LNG_Addon_edmdesigner_previewVM_Tablet", "Tablet");
define("LNG_Addon_edmdesigner_previewVM_Desktop", "Desktop");
define("LNG_Addon_edmdesigner_previewVM_ButtonDescription", "Click on these buttons to preview your e-mail on different devices: ");

define("LNG_Addon_edmdesigner_previewVM_Close", "Close");
define("LNG_Addon_edmdesigner_previewVM_Export", "Export");

define("LNG_Addon_edmdesigner_previewVM_ExportErrorMessage", "Export failed. Please try again later!");
define("LNG_Addon_edmdesigner_previewVM_SendTestEmail", "Send test email");
define("LNG_Addon_edmdesigner_previewVM_SendTestEmailErrorMessage", "Sending test email failed. Please try again later!");
define("LNG_Addon_edmdesigner_previewVM_NotValidEmails", "Please enter a valid email address!");
define("LNG_Addon_edmdesigner_previewVM_NoEmail", "Please enter an email address!");
define("LNG_Addon_edmdesigner_previewVM_TestSubject", "Test email");

define("LNG_Addon_edmdesigner_previewVM_FromLabel", "Send Preview from this Email");
define("LNG_Addon_edmdesigner_previewVM_ToLabel", "Send Preview to this Email");
define("LNG_Addon_edmdesigner_previewVM_SubjectLabel", "Subject");
define("LNG_Addon_edmdesigner_previewVM_SendButton", "Send");

define("LNG_Addon_edmdesigner_previewVM_CheckSpamButton", "Check your email for spam (with autogenerated text body)");



//l10n editorVM
define("LNG_Addon_edmdesigner_editorVM_Title-Template", "Custom template's title: ");
define("LNG_Addon_edmdesigner_editorVM_Title-BuiltInTemplate", "Built-in template's title: ");
define("LNG_Addon_edmdesigner_editorVM_Title-Campaign", "Campaign title: ");

define("LNG_Addon_edmdesigner_editorVM_Preview", "Preview");
define("LNG_Addon_edmdesigner_editorVM_Save", "Save");
define("LNG_Addon_edmdesigner_editorVM_Close", "Close");
define("LNG_Addon_edmdesigner_editorVM_SaveAndClose", "Save and close");
define("LNG_Addon_edmdesigner_editorVM_Next", "Next");
define("LNG_Addon_edmdesigner_editorVM_Back", "Back");

define("LNG_Addon_edmdesigner_editorVM_CancelButton", "Cancel");
define("LNG_Addon_edmdesigner_editorVM_CancelMessage", "Are you sure you want to cancel? Your unsaved data will be lost");

define("LNG_Addon_edmdesigner_editorVM_DefaultSubject", "Default subject");

define("LNG_Addon_edmdesigner_editorVM_Dynamic_Content_Label", "Please select what kind of dynamic content do you want to use:");
define("LNG_Addon_edmdesigner_editorVM_CustomFieldButton", "Insert a Custom Field...");
define("LNG_Addon_edmdesigner_editorVM_UnsubscribeButton", "Insert Unsubscribe Link");
define("LNG_Addon_edmdesigner_editorVM_DynamicContentButton", "Insert a Dynamic Content Tag...");
define("LNG_Addon_edmdesigner_editorVM_SurveyLinkButton", "Insert Survey Link");

define("LNG_Addon_edmdesigner_editorVM_SurveyLinkDefaultText", "Click here to take our survey");


//l10n confirmDeleteVM
define("LNG_Addon_edmdesigner_confirmDeleteVM_Title-Template", "Confirm delete - Template");
define("LNG_Addon_edmdesigner_confirmDeleteVM_Title-BuiltInTemplate", "Confirm delete - Built-in template");
define("LNG_Addon_edmdesigner_confirmDeleteVM_Title-Campaign", "Confirm delete - Campaign");

define("LNG_Addon_edmdesigner_confirmDeleteVM_Description-Template", "Please take into account that your template will be lost forever!");
define("LNG_Addon_edmdesigner_confirmDeleteVM_Description-BuiltInTemplate", "Please take into account that your built-in template will be lost forever!");
define("LNG_Addon_edmdesigner_confirmDeleteVM_Description-Campaign", "Please take into account that your campaign will be lost forever!");

define("LNG_Addon_edmdesigner_confirmDeleteVM_Details", "Details");

define("LNG_Addon_edmdesigner_confirmDeleteVM_Project_Title", "Title");
define("LNG_Addon_edmdesigner_confirmDeleteVM_Project_Category", "Category");
define("LNG_Addon_edmdesigner_confirmDeleteVM_Project_Active", "Active");
define("LNG_Addon_edmdesigner_confirmDeleteVM_Project_CreatedAt", "Created at");
define("LNG_Addon_edmdesigner_confirmDeleteVM_Project_ModifiedAt", "Modified at");

define("LNG_Addon_edmdesigner_confirmDeleteVM_Yes", "Yes");
define("LNG_Addon_edmdesigner_confirmDeleteVM_No", "No");




//l10n templateSelectorWithPreviewVM
define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_Title-Template", "New template");
define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_Title-BuiltInTemplate", "New built-in template");
define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_Title-Campaign", "New campaign");

define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_Name-Template", "Template's name: ");
define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_Name-BuiltInTemplate", "Built-in template's name: ");
define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_Name-Campaign", "Campaign's name: ");

define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_CreateFromSelected", "Create from selected template");
define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_CreateFromScratch", "Create from scratch");

define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_BuiltInTemplates", "Built-in templates");
define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_CustomTemplates", "Custom templates");

define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_Preview_Title", "Preview");
define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_Preview_Mobile", "Mobile");
define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_Preview_Tablet", "Tablet");
define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_Preview_Desktop", "Desktop");
define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_Preview_ButtonDescription", "Click on these buttons to preview your e-mail on different devices: ");

define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_CancelButton", "Cancel");
define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_CancelMessage", "Are you sure you want to cancel?");

define("LNG_Addon_edmdesigner_templateSelectorWithPreviewVM_NoNameMessage", "Please enter a name for your email campaign.");



//l10n subjectAndTextVM
define("LNG_Addon_edmdesigner_subjectAndTextVM_Title", "Subject and text body");
define("LNG_Addon_edmdesigner_subjectAndTextVM_SubjectLabel", "Subject");
define("LNG_Addon_edmdesigner_subjectAndTextVM_TextBodyLabel", "Text body");

define("LNG_Addon_edmdesigner_subjectAndTextVM_Save", "Save");
define("LNG_Addon_edmdesigner_subjectAndTextVM_Cancel", "Cancel");
define("LNG_Addon_edmdesigner_subjectAndTextVM_CancelMessage", "Are you sure you want to cancel? Your unsaved data will be lost");

define("LNG_Addon_edmdesigner_subjectAndTextVM_Close", "Close");
define("LNG_Addon_edmdesigner_subjectAndTextVM_CheckSpamButton", "Check your email for spam");
define("LNG_Addon_edmdesigner_subjectAndTextVM_RegenerateTextVersionButton", "Regenerate text version");



//l10n settings
define("LNG_Addon_edmdesigner_Permissions_Header", "EDMdesigner");

define("LNG_Addon_edmdesigner_Permissions_Templates", "Templates");
define("LNG_Addon_edmdesigner_Permissions_BuiltInTemplates", "Built-in templates");
define("LNG_Addon_edmdesigner_Permissions_Campaigns", "Campaigns");
define("LNG_Addon_edmdesigner_Permissions_Token", "Token - should be enabled");
define("LNG_Addon_edmdesigner_Permissions_Settings", "EDMdesigner settings");





define("LNG_Addon_edmdesigner_Menu_EDMdesigner_Description", "Create stylish responsive e-mail templates in minutes.");

define("LNG_Addon_edmdesigner_apiKey", "API Key");
define("LNG_Addon_edmdesigner_magic", "Magic");
define("LNG_Addon_edmdesigner_languageCode", "Editor's language code");
define("LNG_Addon_edmdesigner_host", "Host");
define("LNG_Addon_edmdesigner_hostError", "Host should start with http:// or https://");

define('LNG_Addon_edmdesigner_Menu_Text', 'Manage built-in responsive templates');
define('LNG_Addon_edmdesigner_Menu_Description', 'Create custom, responsive email templates without coding.');

define('LNG_Addon_edmdesigner_Heading', 'EDMdesigner');
define('LNG_Addon_edmdesigner_Save', 'Save');
define('LNG_Addon_edmdesigner_UserCreated', 'EDMdesigner user successfully created.');

define('LNG_Addon_edmdesigner_Users_Empty', 'There are no EDMdesigner users at this point.');

define('LNG_Addon_edmdesigner_Users', 'EDMdesiger users');
define('LNG_Addon_edmdesigner_Users_Introduction', 'On this page you can configure the API keys for the EDMdesigner per user.');
define('LNG_Addon_edmdesigner_CreateButton', 'Create EDMdesigner User');
define('LNG_Addon_edmdesigner_DeleteButton', 'Delete Selected Users');
define('LNG_Addon_edmdesigner_DeleteAllButton', 'Delete All Users');
define('LNG_Addon_edmdesigner_logsdeleted', 'Selected log entries have been deleted.');
define('LNG_Addon_edmdesigner_all_logsdeleted', 'All log entries have been deleted.');
define('LNG_Addon_edmdesigner_ChooseUsersToDelete_Alert', 'Please choose at least one entry to delete.');
define('LNG_Addon_edmdesigner_APIkey', 'API key');
define('LNG_Addon_edmdesigner_LangEnglish', 'English');
define('LNG_Addon_edmdesigner_LangDutch', 'Dutch');
define('LNG_Addon_edmdesigner_LangGerman', 'German');
define('LNG_Addon_edmdesigner_LangSpanish', 'Spanish');

define('LNG_Addon_edmdesigner_Username', 'Username');
define('LNG_Addon_edmdesigner_Fullname', 'Full name');
define('LNG_Addon_edmdesigner_Language', 'Language');
define('LNG_Addon_edmdesigner_Date', 'Date');
define('LNG_Addon_edmdesigner_Action', 'Action');

define('LNG_Addon_edmdesigner_Manage_Edit', 'Edit');
define('LNG_Addon_edmdesigner_Manage_Delete', 'Delete');
define('LNG_Addon_edmdesigner_SaveButton', 'Save User');
define('LNG_Addon_edmdesigner_CancelButton', 'Cancel');

define('LNG_Addon_edmdesigner_Alert_DeleteSelected', 'Are you sure you want to delete selected EDMdesigner users? This cannot be undone.');
define('LNG_Addon_edmdesigner_Alert_DeleteAll', 'Are you sure you want to delete all EDMdesigner users? This cannot be undone.');

